# Generated by Django 5.2 on 2025-04-30 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('daraja', models.CharField(max_length=50)),
                ('ustoz', models.CharField(max_length=100)),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chegirma', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('yosh', models.IntegerField()),
                ('sana', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name_plural': 'Adminlar'},
        ),
        migrations.AlterModelOptions(
            name='kitob',
            options={'verbose_name_plural': 'Kitoblar'},
        ),
        migrations.AlterModelOptions(
            name='muallif',
            options={'verbose_name_plural': 'Mualliflar'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name_plural': 'Recordlar'},
        ),
        migrations.AlterModelOptions(
            name='talaba',
            options={'verbose_name_plural': 'Talabalar'},
        ),
        migrations.CreateModel(
            name='Izoh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.TextField()),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('baho', models.IntegerField()),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kurs')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Tanlangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kurs')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Xarid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('holat', models.CharField(max_length=100)),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kurs')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profil')),
            ],
        ),
    ]
