# Generated by Django 5.2 on 2025-04-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_kurs_profil_alter_admin_options_alter_kitob_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ful_name', models.CharField(max_length=255)),
                ('course', models.PositiveSmallIntegerField(default=1)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('gpa', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='student/')),
            ],
        ),
    ]
